resources:
  - name: dbp_repo
    type: GitRepo
    configuration:
      gitProvider: GitHub_Integration_Docker                       # <-- Artifactory GitHub integration pipeline
      path: uo405/jfrog-pipelines-docker-cum    # <-- GitHub repo name
      branches:
        include: master

  - name: dbp_image
    type: Image
    configuration:
      registry: Artifactory_Integration_Docker                                # <-- artifactory docker integration pipeline
      sourceRepository: docker-local               # <-- Artifactory repo for docker build
      imageName: cumminspoc.jfrog.io/docker-local/dbp  # < -- repo path to the docker image located in Artifactory
      imageTag: latest
      autoPull: true
      
  - name: dbp_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory_Integration_Docker
      buildName: dbp_build
      buildNumber: 1    

  - name: dbp_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory_Integration_Docker
      buildName: dbp_build
      buildNumber: 1
      

pipelines:
  - name: demo_pipeline_build
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: cumminspoc.jfrog.io/docker-local/dbp  # repo path to the docker image located in Artifactory
          dockerImageTag: ${run_number}
          inputResources:
            - name: dbp_repo
          integrations:
            - name: Artifactory_Integration_Docker                            # <-- artifactory docker integration pipeline

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: docker-local
          integrations:
            - name: Artifactory_Integration_Docker                            # <-- artifactory docker integration pipeline
          inputSteps:
            - name: docker_build
          outputResources:
            - name: dbp_image

      - name: publish_dbp_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: dbp_build_info

      - name: promote_dbp_build
        type: PromoteBuild
        configuration:
          targetRepository: demo-pipelines
          integrations:
            - name: Artifactory_Integration_Docker
          inputResources:
            - name: dbp_build_info
          outputResources:
            - name: dbp_promoted_build_info
